<?php 
/* 
 * Titan Framework 
 * Cache of Language Pack (i18n) 
 * Generated at 31-10-2014 20:04:02 
 */ 

return array (
  'Version' => 'Versão',
  'Author' => 'Autor',
  'Generated by the system' => 'Gerado pelo sistema',
  'Generate PDF' => 'Gerar PDF',
  'Select' => 'Selecione',
  'Version of Document' => 'Versão do Documento',
  'Page' => 'Página',
  'Authentication' => 'Autenticação',
  'Control Number' => 'Número de Controle',
  'WITNESSES' => 'TESTEMUNHAS',
  'Generate Document' => 'Gerar Documento',
  'Attention! You must save the form before you can enter items on this field.' => 'Atenção! Você precisa salvar o formulário antes de inserir itens neste campo.',
  'Are you sure you want to cancel? All changes will be lost.' => 'Tem certeza que deseja cancelar? Todas as alterações serão perdidas.',
  'The file [[1]] was unduly altered or corrupted!' => 'O arquivo [[1]] foi alterado indevidamente ou corrompido!',
  'Warning! The document exists in our database, however this is not your last version. The document that you have on hand is version [1], but is the correct version [2], available at the link below:' => 'Atenção! O documento existe em nossa base de dados, entretanto esta não é sua versão mais atual. O que você têm em mãos é a versão [1], mas a versão correta do documento é a [2], disponível no link abaixo:',
  'The document exists in our database! It\'s available at the link below:' => 'O documento existe em nossa base de dados! Ele está disponível no link abaixo:',
  'This document do not exists in our database or do not be open!' => 'Este documento não existe em nossa base de dados ou não pode ser aberto!',
  'VIEW DOCUMENT' => 'VER DOCUMENTO',
  'GO BACK' => 'VOLTAR',
  'DOCUMENT IS NOT GENERATED' => 'DOCUMENTO AINDA NÃO GERADO',
  'Document Validation' => 'Validação de Documento',
  'Warning! The authenticity of this [1] may be verified by accessing the following Web address: [2]' => 'Atenção! A autenticidade deste [1] pode ser verificada acessando o seguinte endereço Web: [2]',
  'Place the document\'s <span>QR CODE</span> in front of the camera.' => 'Posicione o <span>QR CODE</span> do documento em frente à câmera.',
  'The QR Code is an image like the shown in the figure below:' => 'O QR Code é uma imagem semelhante a mostrada na figura abaixo:',
);